name: Attach build file

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  attach:
    runs-on: ubuntu-latest

    env:
      ZAPRET_TAG: v71.3

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Download Zapret
        env:
          ZAPRET_BUILD_FILE_URL: "https://github.com/bol-van/zapret/releases/download/${{ env.ZAPRET_TAG }}/zapret-${{ env.ZAPRET_TAG }}-openwrt-embedded.tar.gz"
        run: |
          set -euo pipefail
          IFS=$'\n\t'

          echo "::group::Download & unpack Zapret"
          curl -fL "$ZAPRET_BUILD_FILE_URL" | tar -xz --strip-components=1 -C ./opt/zapret/
          echo "::endgroup::"

          echo "::group::Fetch latest Zapret ipset list"
          /opt/zapret/ipset/get_config.sh
          echo "::endgroup::"

      - name: Build package
        id: build
        env:
          PACKAGE: "${{ github.event.repository.name }}"
          MAINTAINER: "${{ github.repository_owner}} <${{ github.repository_owner }}@users.noreply.github.com>"
          DESCRIPTION: "${{ github.event.repository.description }}"
        run: |
          set -euo pipefail
          IFS=$'\n\t'

          VERSION="${GITHUB_REF_NAME#v}"
          BUILD_FILE_NAME="${PACKAGE}_${VERSION}_all.ipk"

          mkdir -p ./CONTROL

          cat > ./CONTROL/control <<EOF
          Package: $PACKAGE
          Version: $VERSION
          Architecture: all
          Maintainer: $MAINTAINER
          Description: $DESCRIPTION
          Depends: coreutils-sleep, coreutils-sort, curl, gzip, ipset, iptables, kmod_ndms, xtables-addons_legacy
          EOF

          cat > ./CONTROL/postinst <<EOF
          #!/opt/bin/busybox sh
          set -euo pipefail
          IFS=$'\n\t'

          /opt/zapret/init.d/sysv/keenetic-zapret start
          EOF

          cat > ./CONTROL/prerm <<EOF
          #!/opt/bin/busybox sh
          set -euo pipefail
          IFS=$'\n\t'

          /opt/zapret/init.d/sysv/keenetic-zapret stop
          EOF

          cat > ./CONTROL/conffiles <<EOF
          /opt/zapret/config
          /opt/zapret/ipset/zapret-hosts-user.txt
          EOF

          chmod 0755 ./CONTROL/postinst ./CONTROL/prerm

          tar --owner=0 --group=0 -czf ./control.tar.gz -C ./CONTROL .
          tar --owner=0 --group=0 -czf ./data.tar.gz ./opt/
          echo "2.0" > ./debian-binary

          tar -czf "./$BUILD_FILE_NAME" debian-binary control.tar.gz data.tar.gz

          echo "build_file_path=./$BUILD_FILE_NAME" >> "$GITHUB_OUTPUT"

      - name: Attach build file to release
        env:
          GH_TOKEN: ${{ github.token }}

          BUILD_TAG: "${{ github.event.release.tag_name }}"
          BUILD_FILE_PATH: "${{ steps.build.outputs.build_file_path }}"
        run: |
          set -euo pipefail
          IFS=$'\n\t'

          gh release upload "$BUILD_TAG" "$BUILD_FILE_PATH" --clobber
