name: Attach build file

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  attach:
    runs-on: ubuntu-latest

    env:
      ZAPRET_TAG: v71.3

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Download Zapret
        env:
          ZAPRET_BUILD_FILE_URL: "https://github.com/bol-van/zapret/releases/download/${{ env.ZAPRET_TAG }}/zapret-${{ env.ZAPRET_TAG }}-openwrt-embedded.tar.gz"
          ZAPRET_IPSET_GET_CONFIG: ./opt/zapret/ipset/get_config.sh
        run: |
          set -euo pipefail
          IFS=$'\n\t'

          echo "::group::Download & unpack Zapret"
          curl -fL "$ZAPRET_BUILD_FILE_URL" | tar -xz --strip-components=1 -C ./opt/zapret/
          echo "::endgroup::"

          echo "::group::Fetch latest Zapret ipset list"
          "$ZAPRET_IPSET_GET_CONFIG"
          echo "::endgroup::"

      - name: Build package
        id: build
        env:
          PACKAGE: "${{ github.event.repository.name }}"
          ARCHITECTURE: all
          MAINTAINER: "${{ github.repository_owner}} <${{ github.repository_owner }}@users.noreply.github.com>"
          DESCRIPTION: "${{ github.event.repository.description }}"
          DEPENDS: |
            coreutils-sleep
            coreutils-sort
            curl
            gzip
            ipset
            iptables
            kmod_ndms
            xtables-addons_legacy

          KEENETIC_ZAPRET_SCRIPT: /opt/zapret/init.d/sysv/keenetic-zapret

          IPSET_CONFIGS: |
            zapret-ip
            zapret-ip6
            zapret-ip-exclude
            zapret-ip-exclude6
            zapret-ip-user
            zapret-ip-user6
            zapret-hosts-user
            zapret-hosts
            zapret-ip-ipban
            zapret-ip-ipban6
            zapret-ip-user-ipban
            zapret-ip-user-ipban6
            zapret-hosts-user-ipban
            zapret-hosts-user-exclude
        run: |
          set -euo pipefail
          IFS=$'\n\t'

          VERSION="${GITHUB_REF_NAME#v}"
          BUILD_FILE_NAME="${PACKAGE}_${VERSION}_${ARCHITECTURE}.ipk"

          mkdir -p ./CONTROL

          cat > ./CONTROL/control <<EOF
          Package: $PACKAGE
          Version: $VERSION
          Architecture: $ARCHITECTURE
          Maintainer: $MAINTAINER
          Description: $DESCRIPTION
          Depends: $(echo "$DEPENDS" | xargs | sed 's/ /, /g')
          EOF

          cat > ./CONTROL/postinst <<EOF
          #!/opt/bin/busybox sh
          set -euo pipefail
          IFS=$'\n\t'

          $KEENETIC_ZAPRET_SCRIPT start
          EOF

          cat > ./CONTROL/prerm <<EOF
          #!/opt/bin/busybox sh
          set -euo pipefail
          IFS=$'\n\t'

          $KEENETIC_ZAPRET_SCRIPT stop
          EOF

          {
            echo "/opt/zapret/config"
            for config in $IPSET_CONFIGS; do
              echo "/opt/zapret/ipset/$config.txt"
              echo "/opt/zapret/ipset/$config.txt.gz"
            done
          } > ./CONTROL/conffiles

          chmod 0755 ./CONTROL/postinst ./CONTROL/prerm

          tar --owner=0 --group=0 -czf ./control.tar.gz -C ./CONTROL .
          tar --owner=0 --group=0 -czf ./data.tar.gz ./opt/
          echo "2.0" > ./debian-binary

          tar -czf "./$BUILD_FILE_NAME" debian-binary control.tar.gz data.tar.gz

          echo "build_file_path=./$BUILD_FILE_NAME" >> "$GITHUB_OUTPUT"

      - name: Attach build file to release
        env:
          GH_TOKEN: ${{ github.token }}

          BUILD_TAG: "${{ github.event.release.tag_name }}"
          BUILD_FILE_PATH: "${{ steps.build.outputs.build_file_path }}"
        run: |
          set -euo pipefail
          IFS=$'\n\t'

          gh release upload "$BUILD_TAG" "$BUILD_FILE_PATH" --clobber
