name: Publish release

on:
  push:
    tags:
      - "v*"

jobs:
  publish:
    runs-on: ubuntu-latest

    env:
      ZAPRET_VERSION: v70.5

    steps:
      - name: Checkout main repository
        uses: actions/checkout@v4

      - name: Download and configuring zapret
        run: |
          ZAPRET_BUILD_FILE="zapret-${{ env.ZAPRET_VERSION }}.tar.gz"
          ZAPRET_BUILD_FILE_URL="https://github.com/bol-van/zapret/releases/download/${{ env.ZAPRET_VERSION }}/$ZAPRET_BUILD_FILE"
          ZAPRET_BUILD_FILE_PATH="/tmp/$ZAPRET_BUILD_FILE"
          ZAPRET_BASE_DIR="opt/zapret"
          ZAPRET_IPSET_GET_CONFIG="$ZAPRET_BASE_DIR/ipset/get_config.sh"

          echo Installing curl...
          sudo apt-get install -y curl

          echo Downloading zapret release...
          curl -fL "$ZAPRET_BUILD_FILE_URL" | tar -xvzf - --strip-components=1 -C "$ZAPRET_BASE_DIR"

          echo Downloading block list...
          "$ZAPRET_IPSET_GET_CONFIG"

      - name: Create a new release
        run: |
          TAG="${GITHUB_REF#refs/tags/}"
          BUILD_FILE="${{ github.event.repository.name }}-$TAG.tar.gz"
          BUILD_FILE_PATH="/tmp/$BUILD_FILE"

          tar -czf "$BUILD_FILE_PATH" --exclude={.git,.github,.gitignore} .
          gh release create "$TAG" "$BUILD_FILE_PATH" --generate-notes
        env:
          GH_TOKEN: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
